name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: dependencies
      run: sudo apt-get install gfortran libopenmpi-dev python3-pytest
    - name: make
      run: make PS_MODEL=./examples/bernoulli.stan
    - name: run
      run: ./build/bernoulli/run data --file=./examples/bernoulli.data.json
    - name: test
      run: pytest test/
