name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: dependencies
      run: sudo apt-get install gfortran libopenmpi-dev
    - name: make
      run: make ./examples/bernoulli
    - name: run
      run: ./examples/bernoulli data --file=./examples/bernoulli.data.json
    - name: test dependencies
      run: |
        sudo apt-get install python3-dev python3-pip python3-pytest libtirpc-dev r-base-dev
        pip3 install -r contrib/requirements.txt
        sudo chmod 775 /usr/local/lib/R/site-library
    - name: test
      run: pytest-3 .
