name: clang-format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get install clang-format
    - name: check
      run: clang-format --Werror --dry-run ./src/*.cpp ./src/polystan/*.hpp
