name: JSS reproducer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: dependencies
      run: sudo apt-get install gfortran libopenmpi-dev python3-pytest
    - name: jss
      run: bash test/jss.sh
